targets:
  $default:
    builders:
      gitsumu|info:
        generate_for:
          - lib/utils/git_info.dart
      dart_mappable_builder:
        options:
          generatedMethods: [ decode, encode, copy, stringify, equals ]