name: Deploy GH pages

on:
  push:
    branches: [ 'deploy' ]
  pull_request:
    branches: [ 'deploy' ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  CI_FLUTTER_VERSION: '3.27.x'

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.CI_FLUTTER_VERSION}}
          cache: true
      - name: Precompile
        run: |
          flutter pub get
          dart run build_runner build -d
      - name: Run flutter analyze
        run: |
          flutter analyze --fatal-infos --fatal-warnings lib
      - name: Run flutter test
        run: |
          flutter test
      - name: Build web
        run: |
          flutter build web --base-href /${{ github.event.repository.name }}/ --release
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: 'github-pages'
          path: build/web/
      - name: Deploy to GH pages
        id: deployment
        uses: actions/deploy-pages@v4